name: build
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            build_folder: bundle/deb
            name: Calc_linux_amd64.deb
            ext: "_amd64.deb"
          - os: windows-latest
            build_folder: 'bundle/msi'
            ext: "_x64.msi"
            name: Calc_windows_x64.msi
          - os: macos-latest
            build_folder: 'bundle/dmg'
            ext: ".dmg"
            name: Calc_macos.dmg
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.10.0
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'pnpm'
      - run: pnpm install
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Install system dependencies (ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update && sudo apt install -y libwebkit2gtk-4.0-dev \
            build-essential \
            curl \
            wget \
            libssl-dev \
            libgtk-3-dev \
            libappindicator3-dev \
            patchelf \
            librsvg2-dev
      - name: Build web
        run: pnpm build
      - name: Build tauri app
        run: pnpm tauri build
      - name: Upload build bundle
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.name }}
          path: ./src-tauri/target/release/${{ matrix.build_folder }}/*${{ matrix.ext }}

