name: build
on: [push]


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - platform: ubuntu-latest
            build_folder: bundle/deb
            ext: "_amd64.deb"
          - platform: windows-latest
            build_folder: ''
            ext: ".x64.msi"
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.10.0
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'pnpm'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Install system dependencies (ubuntu)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt update && sudo apt install libwebkit2gtk-4.0-dev \
            build-essential \
            curl \
            wget \
            libssl-dev \
            libgtk-3-dev \
            libappindicator3-dev \
            patchelf \
            librsvg2-dev
      - name: Build web
        run: pnpm build
      - name: Build tauri app
        run: pnpm tauri build
      - name: Set version
        run: echo ::set-env name=PACKAGE_VERSION::$(node -p "require('./package.json').version")
      - name: Upload build bundle
        uses: actions/upload-artifact@v2
        with:
          name: Calc_{{ env.PACKAGE_VERSION }}{{ matrix.ext }}
          path: ./src-tauri/target/release/{{ matrix.build_folder }}/Calc_{{ env.PACKAGE_VERSION }}{{ matrix.ext }}

